### ISSUE TITLE
Windows 10: 400 - Bad Request

### ISSUE THREAD

**Issue by mihai-dinculescu** [rylev/cargo-nuget#2]
I've been trying to follow along and I've got to the point where the second request is made, the one using the "Location" header URL. It returns 400 Bad Request for me.

Initially I thought that I'm missing something so I've checked out your code. Same issue.

It all works fine in a web browser, with curl, and in postman. I'm on Windows 10. At some point, out of desperation. I gave it a try in WSL. Lo and behold, it all works fine.

I'm posting this here in case some other poor soul ends up banging their head against a wall. It's not you, it's probably surf, or, most likely, http-client.

PS: thank you very much for the awesome videos, Ryan. They are very helpful. Please continue making them!

**Comment by rylev** [comment]
It seems like this is a problem in the surf curl backend. I don't have time to do a full deep dive yet so I'm going to switch to Hyper. We can switch back to surf when this is fixed or when new backends for surf become stable.

**Comment by rylev** [comment]
Fixed by #3
